# Reference here: https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

LineLength:
  Enabled: false

MethodLength:
  Enabled: true
  Max: 25

# Prefer single-quotes

Encoding:
  Enabled: false

GlobalVars:
  Enabled: false
